# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # If language is not "en", override the tutorials with the language-specific ones
      - name: "Pre-build"
        command: |
          if [ "$READTHEDOCS_LANGUAGE" != "en" ]; then
            echo "Overriding tutorials with language-specific ones"
            echo "READTHEDOCS_LANGUAGE: $READTHEDOCS_LANGUAGE"
            cp -r docs/source/locale/${READTHEDOCS_LANGUAGE}/tutorial docs/source
          fi

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: extra-build-requirements.txt
